version: "3"

services:
  app:
    image: node:12-alpine
    restart: always
    working_dir: /app
    command: sh -c "yarn && yarn dev"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - mongodb
    env_file:
      - .env.development

  mongodb:
    image: mongo:latest
    restart: always
    ports:
        - 27017:27017
